from flask import Flask, render_template, request, redirect, url_for
import boto3
import os
from werkzeug.utils import secure_filename

app = Flask(__name__)

# Configure your buckets ,
#by setting the real bucket names that 
# is generated by S3
INPUT_BUCKET = "doc-uploads-w43p0y"
OUTPUT_BUCKET = "doc-translated-w43p0y"

s3 = boto3.client("s3")

@app.route("/")
def index():
    # List translated files
    response = s3.list_objects_v2(Bucket=OUTPUT_BUCKET)
    files = []
    if "Contents" in response:
        for obj in response["Contents"]:
            url = s3.generate_presigned_url(
                "get_object",
                Params={"Bucket": OUTPUT_BUCKET, "Key": obj["Key"]},
                ExpiresIn=3600  # 1-hour expiry
            )
            files.append({"name": obj["Key"], "url": url})
    return render_template("index.html", files=files)

@app.route("/upload", methods=["POST"])
def upload():
    if "file" not in request.files:
        return "No file uploaded", 400
    file = request.files["file"]
    if file.filename == "":
        return "No selected file", 400

    filename = secure_filename(file.filename)
    s3.upload_fileobj(file, INPUT_BUCKET, filename)
    return redirect(url_for("index"))

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
